name: Deploy Backend
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Backend
        run: |
          mvn clean package
        working-directory: ./

      - name: Set variables
        id: vars
        run: |
          echo "TARGET_DIR=/home/backend/brating" >> $GITHUB_OUTPUT
          echo "TIMESTAMP=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
          echo "BACKEND_VERSION=${{ github.sha }}-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.JINOJ_HOST }}
          port: ${{ secrets.JINOJ_PORT }}
          username: ${{ secrets.JINOJ_USER }}
          key: ${{ secrets.JINOJ_KEY }}
          source: "br-web-app/target/br-web-app-*.jar,docker/*"
          target: "${{ steps.vars.outputs.TARGET_DIR }}"
          strip_components: 1

      - name: Create and start container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JINOJ_HOST }}
          port: ${{ secrets.JINOJ_PORT }}
          username: ${{ secrets.JINOJ_USER }}
          key: ${{ secrets.JINOJ_KEY }}
          script: |
            cd ${{ steps.vars.outputs.TARGET_DIR }}
            export BACKEND_VERSION=${{ steps.vars.outputs.BACKEND_VERSION }}
            docker-compose down
            docker-compose up -d --build